apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://localhost:3131
    insecure-skip-tls-verify: true
  name: simulator
contexts:
- context:
    cluster: simulator
    user: simulator
  name: simulator-context
current-context: simulator-context
users:
- name: simulator
  user: {}
